version: "3"
services:
  dutyapp:
    container_name: duty-main
    build: .
    depends_on:
      - dutydb
    links:
      - dutydb:dutydb
    networks:
      - dutynetwork
    ports:
      - "8080:8080"
    environment:
      JDBC_DATABASE_URL: "jdbc:postgresql://dutydb:5432/postgres"
      JDBC_DATABASE_USERNAME: "postgres"
      JDBC_DATABASE_PASSWORD: "postgres"

  dutydb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - dutynetwork

networks:
  dutynetwork:
    driver: bridge